dist: xenial
language: python
python:
- '3.7'
install: pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: mosorio
  password:
    secure: eJuxlgqNNSgPfLBrBDxUMjUdX4YM7A3O/cYqJzY0InsKNdCTePLfOMMdWg7PZ2TQ1HOsadHPpHHYtM3dpICGonWhJ4i938cOxmk8FT38f1RwZZEzzIwQ/Ghx3RZDA84yakOSTK7BGO/0ZMx5gKTyQRanDQoOdWW90KF2gBtnapTEggQYrs/ptf2dA2cEnc76al8T/VUROwcZWRbIGaFLijYjTcZxMi0wKUyRuRUGQOvC4HrN3XHp/oqlYz6JKV9JuJJrT2d+BeNX3dhqWcP3QDpN82Q2ImCsYuOLZSHoVEcGxWFoVtbSyNgw6w5+oWeBNE0y6dO9NobgLAAQB4ENv1AN3v2FVHsWyiGKYf51IwFi40MFsCFB5vWAB+uD6TszBxvc73LIU0M52ULOtR7/qy0uHPfCu7Du7ycSj9c8QJdKow9spbHUk6Bm6VMYpQYJdPvXP96DrbyIRtpkhc4s2EzkqNTWJ3ruYzBpnJYc5D0RqzqQzB+KY3XtChb0Q9N4O6L0XKQIMrcPEox+THXWvb3pdZDh1h78SNnyFhmgVcqKeU62O1Z/NIYuSHDKOZuciuCDkAypgHOId1Db8/H4LgD9CL+XLJMiL8RTup7lGXXQd2fSqNLCtyJ9IAs8guBXD96ODJoJbq26tmc+dlcMrAuHYsQ7wdqQx8N2P7KG7WA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: sirspock/mint_cli
